apiVersion: v1
kind: Service
metadata:
  name: bunny-service-clusterip
spec:
  selector:
    app: bunny-page
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort