apiVersion: v1
kind: Service
metadata:
  name: bunny-page
  namespace: labops
spec:
  type: NodePort
  selector:
    app: bunny-page
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
